### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pavanprakash21** [SnakeSel/libretranslate#1]
Hi @SnakeSel, I was looking for a go module for libretranslate and your package looks to be doing what I wanted. However since there is no License attached to the repo, I can't use it. Would you please mind adding a License to your project?

Best,
Pavan

**Comment by SnakeSel** [comment]
Hi @pavanprakash21, i added a license to the project.
Glad if my code comes in handy. 
One of these days I will rewrite the code to be able to specify the url of the translation server.
